find_library(HIKVISION_LIB
MvCameraControl
PATHS ${PROJECT_SOURCE_DIR}/3rd_party/HIKVISION/lib
)

SET(HIKVISION_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/3rd_party/HIKVISION/include)
FILE(GLOB HIKVISION_INCLUDE_FILES ${PROJECT_SOURCE_DIR}/3rd_party/HIKVISION/include/*.h)

MESSAGE(STATUS "find HIKVISION header files: ${HIKVISION_INCLUDE_FILES}")
MESSAGE(STATUS "find HIKVISION lib files: ${HIKVISION_LIB}")
MESSAGE(STATUS "find HIKVISION header path: ${HIKVISION_INCLUDE_DIR}")